### ISSUE TITLE
validate corrupts patches when adding array then appending

### ISSUE THREAD

**Issue by albanm** [Starcounter-Jack/JSON-Patch#76]
Hello,

You can try the following code:

```
var jsonpatch = require('./src/json-patch');
var patches = [{op: 'add', value: [], path: '/foo'}, {op: 'add', value: 2, path: '/foo/-'}];
jsonpatch.validate(patches, {});
console.log(patches);
```

It outputs:

```
[ { op: 'add', value: [ 2 ], path: '/foo' },
  { op: 'add', value: 2, path: '/foo/-' } ]
```

As you can see the value object of the first patch has been modified. Instead of an empty array it is now an array containing the value of the second patch.

**Comment by baranga** [comment]
This also works with objects:
```
var jsonpatch = require('./src/json-patch');
var patches = [{op: 'add', value: {}, path: '/foo'}, {op: 'add', value: 'a', path: '/foo/a'}];
jsonpatch.validate(patches, {});
console.log(patches);
```

Looks like patch value gets copied by reference instead of deep copy.

**Comment by MarkHerhold** [comment]
How does this work with undefined values? IIRC, this repo tries to respect
undefined fields despite them not being serializable to/from JSON (which is
a bad idea anyway IMO) .

**Comment by baranga** [comment]
@MarkHerhold I don't understand your question. How to deep copy something with a `undefined` in it? That should not happen because you can not express a patch operation with value of `undefined`.

**Comment by MarkHerhold** [comment]
@baranga You are right, it shouldn't happen in the traditional JSON sense, but JSON-Patch treats `undefined` as a first-class citizen. ;)

Here's an example:
```
> var jsonpatch = require('fast-json-patch')
undefined
> var obj = {};
undefined
> jsonpatch.apply(obj, [{op: 'add', path:"/thing", value: undefined}]);
true
> Object.keys(obj)
[ 'thing' ]
> obj.thing
undefined
```

**Comment by baranga** [comment]
@MarkHerhold That still works. `deepClone` only does a JSON encode/decode roundtrip if value is of type `object`. See [json-patch-duplex.ts](https://github.com/Starcounter-Jack/JSON-Patch/blob/6a339cc0c4ffb296e8e816f151530f1f6c2350cc/src/json-patch-duplex.ts#L294).

Is that behaviour covered by the test suites? I run them with my modifications and got same errors as on master.

**Comment by baranga** [comment]
Ok, now I see the issue:
```node
> var jsonpatch = require('./src/json-patch-duplex')
undefined
> var obj = {}
undefined
> jsonpatch.apply(obj, [{op: 'add', path: '/deepThing', value: {undef: undefined}}])
true
> Object.keys(obj)
[ 'deepThing' ]
> Object.keys(obj.deepThing)
[]
```
The last should be:
```node
> Object.keys(obj.deepThing)
[ 'undef' ]
```

**Comment by baranga** [comment]
@MarkHerhold So right now something broken can't be fixed because the lib supports a non standard feature?

**Comment by MarkHerhold** [comment]
No, there are other more expensive clone strategies and implementations.
e.g. lodash's clone.

I personally think we should cut a v1 release, dropping support for
undefined and apply your PR.

**Comment by warpech** [comment]
The part regarding `undefined` is fixed in [1.0.0](https://github.com/Starcounter-Jack/JSON-Patch/releases/tag/1.0.0)

**Comment by baranga** [comment]
This issue is still present. I updated my possible fix #100 to newest version: #134. This comes with a speed penalty.
